### ISSUE TITLE
Add cat/ dog issues

### ISSUE THREAD

**Issue by TaylorKellyCodes** [Triangle-Ops/TTJ-landing#4]
Add more pictures
@AllieGie

**Comment by rachelschipull** [comment]
@TaylorKellyCodes I see you tagged Allie in the comment, so if she should also be assigned to this please feel free to add her.

**Comment by AllieGie** [comment]
@AllieGie just saw this. Tagging myself here.

**Comment by AllieGie** [comment]
Going in a different direction.
